# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           '/:year/:title'
relative_permalinks: false

# Setup
title:               blog.irhh.de
tagline:             'virtualization, management, deployment'
description:         'Just another IT-blog... Focused on virtualization, cloud and web-stuff.'
url:                 'https://blog.irhh.de'
baseurl:             ''

# About/contact
author:
  name:              Rasmus Leissner
  url:               https://irhh.de
  email:             blog@irhh.de

gems:
  - jekyll-sitemap
